issues:
#  new-from-rev: origin/master
linters:
  disable:
    - exhaustivestruct # deprecated
    - scopelint # deprecated
    - interfacer # deprecated
    - varcheck # deprecated
    - deadcode # deprecated
    - nosnakecase # deprecated
    - maligned # deprecated
    - structcheck # deprecated
    - ifshort # deprecated
    - golint # deprecated

    - funlen # игнорируем большие функции в тестах
    - godox # игнорируем TODO/BUG/FIXME метки
    - cyclop # сложность функций
    - gofumpt # TODO непонятная ошибка
    - ireturn # возврат интерфейсов
  enable-all: true
linters-settings:
  exhaustruct:
    exclude:
      - 'Command'
  varnamelen:
   ignore-decls:
    - wg sync.WaitGroup
    - tp *sdktrace.TracerProvider
