version: '2'
services:
  pgsql:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - 16686:16686 # web
      - 14268:14268
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./env/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./env/alerts.yaml:/etc/prometheus/alerts.yml
    extra_hosts:
      - host.docker.internal:host-gateway
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    links:
      - prometheus