// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/product.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	usecase "gitlab.ozon.dev/myasnikov.alexander.s/telegram-bot/internal/usecase"
)

// MockProductUsecaseInterface is a mock of ProductUsecaseInterface interface.
type MockProductUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductUsecaseInterfaceMockRecorder
}

// MockProductUsecaseInterfaceMockRecorder is the mock recorder for MockProductUsecaseInterface.
type MockProductUsecaseInterfaceMockRecorder struct {
	mock *MockProductUsecaseInterface
}

// NewMockProductUsecaseInterface creates a new mock instance.
func NewMockProductUsecaseInterface(ctrl *gomock.Controller) *MockProductUsecaseInterface {
	mock := &MockProductUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockProductUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductUsecaseInterface) EXPECT() *MockProductUsecaseInterfaceMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockProductUsecaseInterface) AddProduct(arg0 usecase.AddProductReqDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductUsecaseInterfaceMockRecorder) AddProduct(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductUsecaseInterface)(nil).AddProduct), arg0)
}

// GetStatistics mocks base method.
func (m *MockProductUsecaseInterface) GetStatistics(arg0 usecase.GetStatisticsReqDTO) (usecase.GetStatisticsRespDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", arg0)
	ret0, _ := ret[0].(usecase.GetStatisticsRespDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockProductUsecaseInterfaceMockRecorder) GetStatistics(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockProductUsecaseInterface)(nil).GetStatistics), arg0)
}
